/* eslint-disable @next/next/no-img-element */
/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head'
import Link from 'next/link'
import { About, Contact, Experience, Header, Hero, Projects, Skills } from '../components'

export default function Home() {
  return (
    <div className='h-screen bg-[#fff] snap-y snap-mandatory overflow-y-scroll z-0 overflow-x-hidden scrollbar scrollbar-track-white scrollbar-thumb-black'>
      <Head>

        <title>Aymen's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      { /* Header */ }

      <Header/>

      { /** Hero */ }

      <section id='hero' className='snap-start'>

        <Hero/>

      </section>

      { /** Abour */ }

      <section id='about' className='snap-center'>

        <About/>

      </section>

      { /** Experience */ }

      <section id='experience' className='snap-center'>

        <Experience/>

      </section>

      { /** Skills */ }

      <section id='skills' className='snap-start'>

        <Skills/>

      </section>

      { /** Projects */ }

      <section id='projects' className='snap-start'>

        <Projects/>

      </section>

      { /** Contact */ }
      
      <section id='contact' className='snap-start'>

        <Contact/>

      </section>

      <Link href="#hero">
        <footer className='sticky bottom-5 w-full cursor-pointer'>
          <div className='flex items-center justify-center'>
            <img className='w-10 h-10 rounded-full filter grayscale hover:grayscale-0 cursor-pointer' src={"https://dummyimage.com/720x400"} alt="" />
          </div>
        </footer>
      </Link>

    </div>
  )
}
